import {
  ArrowLeft,
  Check,
  CircleCheck,
  CircleHelp,
  Code2,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  FileJson,
  Folder,
  FolderOpen,
  Globe,
  HelpCircle,
  History,
  Info,
  LayoutGrid,
  Hand,
  MousePointerClick,
  Palette,
  Rows2,
  Search,
  SearchX,
  Settings,
  Settings2,
  Star,
  Trash2,
  TriangleAlert,
  Upload,
  X,
  ChevronRight,
} from '@lucide/icons';

export const uiIcons = {
  'arrow-left': ArrowLeft,
  check: Check,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'code-2': Code2,
  database: Database,
  download: Download,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  'file-json': FileJson,
  folder: Folder,
  'folder-open': FolderOpen,
  globe: Globe,
  'help-circle': HelpCircle,
  history: History,
  info: Info,
  'layout-grid': LayoutGrid,
  hand: Hand,
  'mouse-pointer-click': MousePointerClick,
  palette: Palette,
  'rows-2': Rows2,
  search: Search,
  'search-x': SearchX,
  settings: Settings,
  'settings-2': Settings2,
  star: Star,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  x: X,
  'chevron-right': ChevronRight,
};
