map "$uri:$http_remote_user" $json_file {
    ~*^/services\.json:.+$   /services.$http_remote_user.json;
    default                  $uri;
}

server {
    listen 8080;
    server_name localhost;

    root /app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.json$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;

        try_files $json_file =404;
    }
}
